language: python
python:
  - "3.6"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

# command to run tests
script:
  - pytest --with-coverage tests/test_diary_entries.py

after_success:
  - coveralls
  - coverage report
